services:
  backend:
    build:
      context: ../../
      dockerfile: docker_dt/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../api/.env
    volumes:
      - ../../api/media:/app/media
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

