services:
  backend:
    build:
      context: ../../
      dockerfile: backend/docker/Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - ../../backend/api/.env

    volumes:
      - ../../backend/api/media:/app/media

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
